### ISSUE TITLE
Bundled normal is annoying

### ISSUE THREAD

**Issue by kex-y** [ImperialCollegeLondon/group-theory-game#8]
I have a lot of issues with bundled normal. 
- A lot of definitions need to be written twice for both subgroups and normal subgroups (lattice structure, map and comap, quotient.map and comap etc.).
- A lot of lemmas can't be stated easily (I would like to write quotient.comap H is normal iff H is. This can only be represented by a definition for the forward direction and an unbundled prop for the reverse)

**Comment by kbuzzard** [comment]
So you think normal should be...what? A predicate on `subgroup`? 

The one advantage you have with bundled normal is that you can normal.comap as opposed to something like subgroup.ncomap

**Comment by kex-y** [comment]
I think the `is_normal` predicate from mathlib is the best approach. 
I think it will be better to only use `subgroup.comap` and a lemma `normal.is_normal_comap` instead of two definitions and two sets of APIs which is what we have now.

**Comment by kex-y** [comment]
Okay, after working a bit with the mathlib version of normal, I see the disadvantages of using the unbundled version - a lot of properties don't get inferred automatically especially when working with quotients. I think our current version has enough benefits to justify it being bundled. I'm closing this issue.
